package com.rms.resourcemanagement.infrastructure.config.db.schema;

import com.rms.resourcemanagement.entity.baselocation.model.BaseLocation;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;

import java.util.List;

@Entity
@Table(name = "RentalCopmany")
public class BaseLocationSchema extends UserSchema {

//  @UniqueCNPJ(message = "{Unique.rentalCompany.CNPJ}")
  @NotBlank
//  @CNPJ(message = "{Size.rentalCompany.CNPJ}")
  @Column(unique = true)
  private String cnpj;

  @NotBlank
  @Column(length = 50)
  private String city;

  @OneToMany(cascade = CascadeType.REMOVE, mappedBy = "rentalCompany")
  private List<RentalSchema> rentals;

  public BaseLocationSchema(BaseLocation rentalCompany) {
    super(rentalCompany.getId(), rentalCompany.getUsername(), rentalCompany.getName(), rentalCompany.getEmail(), rentalCompany.getPassword());
    this.cnpj = rentalCompany.getCnpj();
    this.city = rentalCompany.getCity();

    this.role = "ROLE_RENTALCOMPANY";
  }

  public BaseLocationSchema() {
    this.role = "ROLE_RENTALCOMPANY";
  }


  public String getCnpj() {
    return cnpj;
  }

  public void setCnpj(String cnpj) {
    this.cnpj = cnpj;
  }

  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public List<RentalSchema> getRentals() {
    return rentals;
  }

  public BaseLocation toRentalCompany() {
    BaseLocation rentalCompany = new BaseLocation(
            this.getUsername(),
            this.getPassword(),
            this.getName(),
            this.getEmail(),
            this.cnpj,
            this.city
    );

    rentalCompany.setId(this.getId()); // transform the schema id (generated by database) to customer entity id

    return rentalCompany;
  }

}
